.github/app/app/urls.py
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView,
)

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('api/schema/', SpectacularAPIView.as_view(), name='api-schema'),
    # path('api/docs', SpectacularSwaggerView.as_view(url_name='api-schema'), name='api-docs'),
    path('', include('core.urls')),
    path('api/user/', include('user.urls')),
    path('api/kurs/', include('kurs.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

.github/app/core/urls.py
from django.urls import path
from django.contrib import admin
from django.contrib.auth import views as auth_views

from core.views import *

urlpatterns = [
    path('' , Index , name="index-admin"),
    path('login/' , loginView , name="login"),
    path('logout/', logoutView, name="logout"),

    # Erstelle Daten
    path('create-user/', createUser, name='create-user'),
    path('create-kursleiter/', createKursleiter, name='create-kursleiter'),
    path('create-tutor/', createTutor, name='create-tutor'),
    path('create-dozent/', createDozent, name='create-dozent'),
    
    path('create-kurs/', createKurs, name='create-kurs'),
    path('create-blatt/', createBlatt, name='create-blatt'),

    # Liste Daten
    path('list-user/', listUser, name='list-user'),
    path('list-kursleiter/', listKursleiter, name='list-kursleiter'),
    path('list-tutor/', listTutor, name='list-tutor'),
    path('list-dozent/', listDozent, name='list-dozent'),
    
    path('list-kurs/', listKurs, name='list-kurs'),
    path('list-blatt/', listBlatt, name='list-blatt'),

    # Erhalte Profil
    path('get-user/<str:id>/', get_user_profile, name='get-user'),
    path('get-kursleiter/<str:id>/', get_kursleiter_profile, name='get-kursleiter'),
    path('get-tutor/<str:id>/', get_tutor_profile, name='get-tutor'),
    path('get-dozent/<str:id>/', get_dozent_profile, name='get-dozent'),

    path('get-kurs/<str:id>/', get_kurs_info, name='get-kurs'),
    path('get-blatt/<str:id>/', get_blatt_info, name='get-blatt'),

    # Update Profil
    
    # Lösche Profil

    
]

.github/app/user/urls.py
"""
Ansicht für die User API
"""
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token
from user import views

urlpatterns = [
    path('login/', obtain_auth_token, name='login'),
    path('logout/', views.logout_view, name='logout'),


    #path('istutor/', views.TutorView),



    # User
    path('create-user/', views.CreateUserView.as_view(), name='create-user'),
    path('list-user/', views.UserListView.as_view(), name='list-user'),
    path('get-user/<str:pk>/', views.UserDetailView.as_view(), name='get-user'),
    # path('update-user/<str:pk>', views.UserDetailView.as_view(), name='update-user'),
    # path('delete-user/<str:pk>', views.UserDetailView.as_view(), name='delete-user'),

    # Kursleiter
    path('create-kursleiter/', views.CreateKursleiterView.as_view(), name='create-kursleiter'),
    path('list-kursleiter/', views.KursleiterListView.as_view(), name='list-kursleiter'),
    path('get-kursleiter/<str:pk>/', views.KursleiterDetailView.as_view(), name='get-kursleiter'),
    #path('create-kursleiterprofile/', views.CreateKursleiterView.as_view(), name='create-kursleiterprofile'),
    
    
    # Tutor
    path('create-tutor/', views.CreateTutorView.as_view(), name='create-tutor'),
    path('list-tutor/', views.TutorListView.as_view(), name='list-tutor'),
    path('get-tutor/<str:pk>/', views.TutorDetailView.as_view(), name='get-tutor'),
    # path('create-tutorprofile/', views.CreateTutorView.as_view(), name='create-tutorprofile'),
    

    # Dozent
    path('create-dozent/', views.CreateDozentView.as_view(), name='create-dozent'),
    path('list-dozent/', views.DozentListView.as_view(), name='list-dozent'),
    path('get-dozent/<str:pk>/', views.DozentDetailView.as_view(), name='get-dozent'),
    # path('detail-dozent/<str:pk>/', views.DozentDetailView.as_view(), name='detail-dozent'),
]

.github/app/core/models.py
"""
Datbank mMdels.
"""
from django.db import models
from django.conf import settings

from django.contrib.auth import get_user_model

from django.contrib.auth.models import (
    AbstractBaseUser, BaseUserManager, PermissionsMixin
)

from django.db.models.signals import post_save
from django.dispatch import receiver

from rest_framework.authtoken.models import Token
from django.contrib.auth.hashers import make_password


class UserManager(BaseUserManager):
    """Manager for users."""

    def create_user(self, email, password=None, **extrafields):
        """Erstellt, speichert und gibt als Rückgabewert User zurück."""

        user = self.model(
            email=self.normalize_email(email), 
            **extrafields
            )
        print('Hier usermanager')
        print(password)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, email, password=None, **extrafields):
        """Erstellt und gibt als Rückgabewert Superuser zurück."""
        extrafields.setdefault('is_active', True)
        extrafields.setdefault('is_staff', True)
        extrafields.setdefault('is_superuser', True)
        extrafields.setdefault('is_admin', True)

        user = self.create_user(
            email, 
            password, 
            **extrafields
        )
        return user


class User(AbstractBaseUser, PermissionsMixin):
    """User in the system."""
    class Rolle(models.TextChoices):
        Admin = "Admin", 'Admin'
        Tutor = "Tutor", 'Tutor'
        Kursleiter = "Kursleiter", 'Kursleiter'
        Dozent = "Dozent", 'Dozent'

    base_user=Rolle.Admin

    rolle = models.CharField(("Rolle"), max_length=10, choices=Rolle.choices)
    email = models.EmailField(max_length=255, unique=True)
    vorname = models.CharField(max_length=255, blank=True)
    nachname = models.CharField(max_length=255, blank=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser=models.BooleanField(default=False)

    is_admin = models.BooleanField(default=False)
    is_dozent = models.BooleanField(default=False)
    is_kursleiter = models.BooleanField(default=False)
    is_tutor = models.BooleanField(default=False)

    objects = UserManager()

    class Meta:
        verbose_name_plural = "Benutzer"

    USERNAME_FIELD = 'email'

    # def has_perm(self , perm, obj = None):
    #     return self.is_admin
      
    # def has_module_perms(self , app_label):
    #     return True

    def save(self, *args, **kwargs):
        if not self.pk:
            print('User save: ')
            print(self.base_user)
            print(self.rolle)
            self.rolle = self.rolle
            # email senden verifizieren active auf True setzen und
            # passwort setzen
            return super().save(*args, **kwargs)




###################################


class Kurs(models.Model):
    """Kurse im System"""
    kurs = models.CharField(max_length=50, unique=True)
    beschreibung = models.TextField(blank=True)
    ref_id = models.CharField(max_length=100, unique=True)
    # dozent = models.ForeignKey(Dozent, on_delete=models.CASCADE, related_name='kurs')

    class Meta:
        verbose_name_plural = "Kurse"

    def __str__(self):
        return f"{self.kurs}"


class Blatt(models.Model):
    """Übungsblätter im System"""
    ass_name = models.CharField(max_length=200)
    ass_id = models.CharField(max_length=100, unique=True)
    kurs = models.ForeignKey(Kurs, on_delete=models.CASCADE, default=None)

    class Meta:
        verbose_name_plural = "Übungsblätter"

    def __str__(self):
        return f"{self.ass_name}"
    



###############################################

class TutorManager(UserManager):
    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args , **kwargs)
        queryset = queryset.filter(rolle = User.Rolle.Admin)
        return queryset


class Tutor(User):
    base_role = User.Rolle.Tutor

    objects = TutorManager()

    class Meta:
        proxy = True
        verbose_name_plural = "Tutoren"

    # def save(self , *args , **kwargs):
    #     self.base_user = User.Rolle.Tutor
    #     self.is_tutor = True
    #     return super().save(*args , **kwargs)


class TutorProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    kurs = models.ForeignKey(Kurs, on_delete=models.CASCADE,null=True, blank=True)
    tutor_id = models.CharField(max_length=100, null=True, blank=True,default=None)
    arbeitsstunden = models.FloatField(default=0)

    class Meta:
        verbose_name_plural = "Tutor Profil"

    def __str__(self):
        return f"{self.user.email}"


#####################################


class KursleiterManager(UserManager):

    def get_queryset(self, *args, **kwargs):
        results = super().get_queryset(*args, **kwargs)
        return results.filter(rolle=User.Rolle.Kursleiter)


class Kursleiter(User):
    base_role = User.Rolle.Kursleiter

    objects = KursleiterManager()

    class Meta:
        proxy = True
        verbose_name_plural = "Kursleiter"

    def save(self  , *args , **kwargs):
        self.base_user = User.Rolle.Kursleiter
        self.is_kursleiter = True
        return super().save(*args , **kwargs)


class KursleiterProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    kurs = models.ForeignKey(Kurs, on_delete=models.CASCADE,null=True, blank=True)

    class Meta:
        verbose_name_plural = "Kursleiter Profil"

    def __str__(self):
        return f"{self.user.email}"


#########################


class Dozent(User):
    base_user = User.Rolle.Dozent

    class Meta:
        proxy = True
        verbose_name_plural="Dozenten"


class DozentProfile(models.Model):
    class Titel(models.TextChoices):
        Prof = "Prof", 'Prof'
        Dr = "Dr", 'Dr'

    titel = models.CharField(("Titel"), max_length=10, choices=Titel.choices, default='Prof.')
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "Dozent Profil"

        
 #############


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_profile(sender, instance=None, created=False, **kwargs):
    if created and instance.is_kursleiter == True:
        print("Kursleiterprofil und Token wurde erstellt")
        KursleiterProfile.objects.create(user=instance)
        Token.objects.create(user=instance)
    if created and instance.is_tutor == True:
        print("Tutorprofil und Token wurde erstellt")
        print(instance.email)
        TutorProfile.objects.create(user=instance)
        Token.objects.create(user=instance)
    if created and instance.is_dozent == True:
        print("Dozent Profil und Token wurde erstellt")
        DozentProfile.objects.create(user=instance)
        Token.objects.create(user=instance)


@receiver(post_save, sender=Dozent)
def create_dozent_profile(sender, instance=None, created=False, **kwargs):
    if created and instance.is_dozent == True:
        print('ich bin hier post save dozent profile')
        DozentProfile.objects.create(user=instance)


@receiver(post_save, sender=Kursleiter)
def create_user_profile(sender, instance=None, created=False, **kwargs):
    if created and instance.is_kursleiter == True:
        print('ich bin hier post save kursleiter profile')
        KursleiterProfile.objects.create(user=instance)


@receiver(post_save, sender=Tutor)
def create_tutor_profile(sender, instance=None, created=False, **kwargs):
    if created and instance.is_tutor == True:
        print('ich bin hier post save tutor profile')
        TutorProfile.objects.create(user=instance)


# @receiver(post_save, sender=User)
# def create_profile(sender, instance, created, **kwargs):
#     if created and instance.is_tutor == True:
#         print("1")
#         TutorProfile.objects.create(instance=instance)
#     if created and instance.rolle == "Kursleiter":
#         print("2")
#         KursleiterProfile.objects.create(user=instance)
#     if created and instance.rolle == "Tutor":
#         print("3")
#         TutorProfile.objects.create(user=instance)
#     if created and instance.rolle == "Dozent":
#         print("4")
#         DozentProfile.objects.create(user=instance)

.github/app/core/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from core.models import *
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm


class AuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = '__all__'


class CostumUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        exclude = ['password', 'last_login',]


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = User
        fields = ("email",)


# class SignUpForm(UserCreationForm):
#     email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

#     class Meta:
#         model = User
#         fields = ('email', 'password1', 'password2', )


class LoginForm(forms.Form):
    email = forms.EmailField(max_length=200, required=True)
    password = forms.CharField(widget=forms.PasswordInput)


################################## 


# class UserForm(forms.ModelForm):
#     """ Bei Admin eingaben werden die fields ignoriert """
#     class Meta:
#         model = User
#         exclude=['rolle', 'last_login', 'groups', 'user_permissions', 'password']

#         labels = {
#             'email': _('Email'),
#             'vorname': _('Vorname'),
#             'nachname': _('Nachname'),
#         }


class KursleiterForm(forms.ModelForm):
    class Meta:
        model = Kursleiter
        exclude=['last_login', 'groups', 'user_permissions', 'password']

        labels = {
            'email': _('Email'),
            'vorname': _('Vorname'),
            'nachname': _('Nachname'),
            'kurs_name': _('Kurs'),
            'role': _('Rolle'),
        }


# class KursleiterProfileForm(forms.Modelform):
#     class Meta:
#         model = KursleiterProfile
#         fields = '__all__'
#         # exclude = ['']


########################


class TutorForm(forms.ModelForm):
    class Meta:
        model = Tutor
        fields = '__all__'
    
        # exclude=['rolle', 'last_login', 'groups', 'user_permissions', 'password']


class TutorProfileForm(forms.ModelForm):
    class Meta:
        model = TutorProfile
        fields = '__all__'
        # fields = ['user, tutor_id, kurs, arbeitsstunden']

        
##############################


class DozentForm(forms.ModelForm):
    class Meta:
        model = Dozent
        # fields = '__all__'
        exclude=['rolle', 'last_login', 'groups', 'user_permissions', 'password']
        
        # labels = {
        #     'title': _('Titel'),
        #     'vorname': _('Vorname'),
        #     'nachname': _('Nachname'),
        # }

        # error_messages = {
        #     'titel':{
        #         'required': _('Title has to be choosen')
        #     },
        #     'vorname':{
        #         'required': _('First name has to be entered')
        #     },
        #     'nachname': _('Last name has to be entered')
        # },


############################


class KursForm(forms.ModelForm):
    class Meta:
        model = Kurs
        fields = '__all__'
        # exclude=['dozent']

        # labels := Bezeichnung
        # labels = {
        #     'kurs': _('Kursname eingeben'),
        #     'beschreibung': _('Beschreibung eingegeben'),
        #     'kursleiter': _('Kursleiter eingeben'),
        # }
        # error_messages = {
        #     fields : {
        #         'kurs': {
        #             'required': _('Module name has to be entered')
        #         },
        #         'beschreibung': {
        #             'required': _('Description has to be entered')
        #         },
        #         'Kursleiter': {
        #             'required': _('Teacher has to be entered')
        #         },
        #     }
        # }


class BlattForm(forms.ModelForm):
    class Meta:
        model = Blatt
        fields = '__all__'


# class TutorProfileForm(forms.ModelForm):
#     class Meta:
#         model=TutorProfile
#         fields='__all__'

#         label = {
#             'user': _('Vorname'),
#             'tutor_id': _('ID'),
#             'kurs': _('Kurs'),
#             'arbeitsstunden': _('Arbeitsstunden'),
#             'anzahl_korrekturen': _('Anzahl Korrekturen'),
#         }
#         error_messages = {
#             'user':{
#                 'required': ('Vorname angeben')
#             }
#         }

.github/app/core/templates/user/createblatt.html
<html style="background: lightblue">
<body >
    <p>Blatt erstellen</p>
    {% if messages %}
    {% for i in messages %}
    {}
    <form method="post">
    {% csrf_token %}    
    {{form.as_p}}
    <input type="submit" value="Submit"/>
    </form>
</body>
</html>

.github/app/core/templates/user/createdozent.html
<html style="background: lightblue">

    <p>Dozent erstellen</p>

    <!-- <form method="post">
    {% csrf_token %}
    <label for="titel">Titel:</label><br>
    <select id="titel" name="titel">
        <option value="prof">Prof.</option>
        <option value="dr">Doktor</option>
    </select>
    </br>
        <label for="vorname">Vorname:</label><br>
        <input name="vorname" type="text" id="vorname">
    </br>
        <label for="nachname">Nachname:</label><br>
        <input name="nachname" type="text" id="nachname">
    </br>  
    </br>      
        <input type="submit" value="Submit">
    </form> -->

      <form method="post">
        {% csrf_token %} 
        {{form.as_p}}
        <!-- <label for="{{form.title.id_for_label}}"> {{form.titel.label}}</label>{{form.titel}}
        <br />

        <label for="{{form.name.id_for_label}}">{{form.name.label}}</label>
        <br />
          {{form.name}}
          <br />
        <label for="{{form.nachname.id_for_label}}">{{form.nachname.label}}</label>
          <br />
          {{form.nachname}}
          <br /> -->
        <input type="submit" value="Submit" />
      </form>

</html>

.github/app/core/templates/user/createkurs.html
<html style="background: lightblue">
<body >
    <p>Kurs erstellen</p>
    <form method="post">
    {% csrf_token %}    
    {{form.as_p}}

    <!-- <label for="id_kurs">Kursname eingeben:</label>
    <input type="text" name="kurs" maxlength="50" required="" id="id_kurs">
    <br>
    <p>
        <label for="id_beschreibung">Beschreibung eingegeben:</label> 
        <textarea name="beschreibung" cols="40" rows="10" id="id_beschreibung"></textarea>
    </p>
    <p>
        <label for="id_ref_id">Ref id:</label> 
        <input type="text" name="ref_id" maxlength="100" required="" id="id_ref_id">
    </p>
    <p> -->
    <!-- <select name="dozent" required="" id="id_dozent">
        <!-- <option value="ID">Datenbanken</option> -->
        <!--{% for i in dozent %}
            <option value="{{i.id}}">{{i.title}} {{i.vorname}} {{i.nachname}}</option>
        {% endfor %}
    </select>
    </p> -->


    <input type="submit" value="Submit">
    </form>
</body>
</html>

.github/app/core/templates/user/createtutor.html
<html style="background: lightblue">
    <p>Tutor erstellen</p>

    <form method="post">
    {% csrf_token %}
    {{form.as_p}}

    <input type="submit" value="Submit">
    </form>

</html>


<!-- <button type="button"><a href="/">Zurück</a></button>

<h2>Tutor erstellen: </h2>
<form method="post" style="background: lightblue">  
  <input type="hidden" name="csrfmiddlewaretoken" value="ykVtQLAdVdtjknZC89y9WPkCA6baMP1tDH17c7OVhqhCcowBnIdtcfu138zXNofx"> 

    <div class="form-group">
        <label for="id_vorname">Vorname:</label> 
        <input type="text" class="form-control" name="vorname" maxlength="255" id="id_vorname"></div>
    <div class="form-group">
        <label for="id_nachname">Nachname:</label> 
        <input type="text" class="form-control" name="nachname" maxlength="255" id="id_nachname"></div>
    <div class="form-group">
        <label for="id_email">Email:</label> 
        <input type="email" class="form-control" name="email" maxlength="255" autofocus="" required="" id="id_email"></div>       
    <div class="form-group">
        <label for="id_tutor_id">Matrikelnummer:</label> 
        <input type="text" class="form-control" name="tutor_id" maxlength="255" id="id_tutor_id"></div>
    <div class="form-group">
        <label for="id_rolle">Rolle:</label> 
        <select name="rolle" required="" id="id_rolle">
            <option value="Tutor">Tutor</option>
        </select></div>

    {% if kurse %}
        <p><label for="id_kurs">Kurs</label>

        <select name="kurs" required="" id="id_kurs">
        {% for i in kurse %}
            <option value="{{ i.kurs }}">{{ i.kurs }}</option>
        {% endfor%}
        </select>
        </p>
    {% endif %}
    
    <p><label for="id_arbeitsstunden">Arbeitsstunden:</label> 
        <input type="text" class="form-control" name="arbeitsstunden" maxlength="255" id="id_arbeitsstunden"></p>
    <p><label for="id_is_active">Is active:</label> 
        <input type="checkbox" name="is_active" id="id_is_active" checked=""></p>
    <p><label for="id_is_staff">Is staff:</label> 
        <input type="checkbox" name="is_staff" id="id_is_staff"></p>
    <p><label for="id_is_superuser">Is superuser:</label> 
        <input type="checkbox" name="is_superuser" id="id_is_superuser"></p>
 
    <input type="submit" value="Submit">
  </form> -->

.github/app/core/templates/user/createuser.html
<!-- <html style="background: lightblue">
    <p>Benutzer erstellen</p>
    <form method="post">
        {% csrf_token %}
        <label for="email">Email:</label><br/>
        <input name="email" type="text" id="email">
    </br>
        <label for="vorname">Vorname:</label><br>
        <input name="vorname" type="text" id="vorname">
    </br>
        <label for="nachname">Nachname:</label><br>
        <input name="nachname" type="text" id="nachname">
    <br>
        <input type="submit" value="Submit">
    </form>
</html> -->


<!-- <form method="post">
    {% csrf_token %} {{form.as_p}}
    <!-- <label for="{{form.email.id_for_label}}">{{form.email.label}}</label>{{form.titel}}
    <br />

    <label for="{{form.vorname.id_for_label}}">{{form.vorname.label}}</label>{{form.vorname}}
    <br />

    <label for="{{form.nachname.id_for_label}}">{{form.nachname.label}}</label>{{form.nachname}}
    <br /> -->

    <!-- <input type="submit" value="Submit" /> -->
<!-- </form> -->


<button type="button"><a href="/">Zurück</a></button>

<form method="post" style="background: lightblue">  
    <input type="hidden" name="csrfmiddlewaretoken" value="ykVtQLAdVdtjknZC89y9WPkCA6baMP1tDH17c7OVhqhCcowBnIdtcfu138zXNofx"> <p><label for="id_rolle">Rolle:</label> <select name="rolle" required="" id="id_rolle">
    <option value="" selected="">---------</option>
  
    <option value="Admin">Admin</option>
  
    <option value="Tutor">Tutor</option>
  
    <option value="Kursleiter">Kursleiter</option>
  
    <option value="Dozent">Dozent</option>
  
  </select></p>
  <p><label for="id_email">Email:</label> <input type="email" name="email" maxlength="255" autofocus="" required="" id="id_email"></p>
  <p><label for="id_vorname">Vorname:</label> <input type="text" name="vorname" maxlength="255" id="id_vorname"></p>
  <p><label for="id_nachname">Nachname:</label> <input type="text" name="nachname" maxlength="255" id="id_nachname"></p>
  <p><label for="id_is_active">Is active:</label> <input type="checkbox" name="is_active" id="id_is_active" checked=""></p>
  <p><label for="id_is_staff">Is staff:</label> <input type="checkbox" name="is_staff" id="id_is_staff"></p>
  <p><label for="id_is_superuser">Is superuser:</label> <input type="checkbox" name="is_superuser" id="id_is_superuser"></p>
  <p><label for="id_password1">Password:</label> <input type="password" name="password1" autocomplete="new-password" required="" id="id_password1"> <span class="helptext"></span></p><ul><li>Your password can’t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can’t be a commonly used password.</li><li>Your password can’t be entirely numeric.</li></ul><p></p>
  <p><label for="id_password2">Password confirmation:</label> <input type="password" name="password2" autocomplete="new-password" required="" id="id_password2"> <span class="helptext">Enter the same password as before, for verification.</span></p> 
    
    
    
    <!--  -->
    <input type="submit" value="Submit">
  </form>

.github/app/core/templates/user/form.html
<button type='button'><a href='{% url 'index-admin' %}'>Zurück</a></button>

<!--Kurse Formular-->
<form method="post" style="background: lightblue">  
  {% csrf_token %} {{form.as_p}} 
  <input type="submit" value="Submit" />
</form>

.github/app/core/templates/user/get-dozent-profile.html
{% if user %}
<p>{{user.email}}</p>
<p>{{user.vorname}}</p>
<p>{{user.nachname}}</p>
{% endif %}

<button>Bearbeiten</button>
<button>Löschen</button>

.github/app/core/templates/user/get-kursleiter-profile.html
{% if user %}
<p>{{user.email}}</p>
<p>{{user.vorname}}</p>
<p>{{user.nachname}}</p>
{% endif %}


<button>Bearbeiten</button>
<button>Löschen</button>

.github/app/core/templates/user/get-tutor-profile.html
{% if user %}
<p>{{user.email}}</p>
<p>{{user.vorname}}</p>
<p>{{user.nachname}}</p>
{% endif %}

<button>Bearbeiten</button>
<button>Löschen</button>

.github/app/core/templates/user/get-user-profile.html
{% if user %}
<p>{{user.email}}</p>
<p>{{user.vorname}}</p>
<p>{{user.nachname}}</p>
{% endif %}

<button>Bearbeiten</button>
<button>Löschen</button>

.github/app/core/templates/user/index-admin.html
<!DOCTYPE html>
<html lang="en" style="background: lightblue">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <link href="css/index.css" rel="stylesheet" />
    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <title>HHU - sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3</title>
  </head>

  <body>

  {% if user.groups == 'ADMIN'%}
      <h2>Admin Ansicht </h2>
  {% endif %}

  {%block content %}
  {% csrf_token %}
    <div class="mx-auto w-50" style="width:200px; height: 200px; padding: 180px;">
      <!-- Benutzer ERSTELLEN -->
      <button class="m-2" type="button"><a href="{% url 'create-user' %}">Admin erstellen</a></button><br>
      <button class="m-2" type="button"><a href="{% url 'create-kursleiter' %}">Kursleiter erstellen</a></button><br>
      <button class="m-2" type="button"><a href="{% url 'create-tutor' %}">Tutor erstellen</a></button><br>
      <button class="m-2" type="button"><a href="{% url 'create-dozent' %}">Dozent erstellen</a></button><br>

      <!-- Kurs und Übungsblätter ERSTELLEN -->
      <button class="m-2" type="button"><a href="{% url 'create-kurs' %}">Kurs erstellen</a></button><br>
      <button class="m-2" type="button"><a href="{% url 'create-blatt' %}">Blatt erstellen</a></button><br>

      <!-- Benutzer Liste anzeigen -->
      <button class="m-2" type="button"><a href="{% url 'list-user' %}">Alle Benutzer einsehen</a></button><br>
      <button class="m-2" type="button"><a href="{% url 'list-kursleiter' %}">Alle Kursleiter einsehen</a></button><br>
      <button class="m-2" type="button"><a href="{% url 'list-tutor' %}">Alle Tutor einsehen</a></button>

    </div>
    {% endblock %}
  </body>
</html>